---
- name: Deploy project to Raspberry Pi
  hosts: all
  tasks:
    - name: Install dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - git
    - name: Clone Wyoming Satellite
      ansible.builtin.git:
        repo: 'https://github.com/rhasspy/wyoming-satellite.git'
        dest: ~/wyoming-satellite
        version: v1.2.0