---
- name: Download Dependencies and set up satellite
  hosts: all
  tasks:
    - name: Check Swapfile meets size target
      become: true
      ansible.builtin.shell:
        cmd: "grep -q '^CONF_SWAPSIZE={{ desired_swap_size }}$' /etc/dphys-swapfile || echo 'not_found'"
      register: swapsize_check
      changed_when: false

    - name: "Resize swap to {{ desired_swap_size }}"
      become: true
      ansible.builtin.lineinfile:
        path: /etc/dphys-swapfile
        regexp: '^CONF_SWAPSIZE='
        line: 'CONF_SWAPSIZE={{ desired_swap_size }}'
      when: swapsize_check.stdout == "not_found"

    - name: Reboot if the line was replaced
      become: true
      ansible.builtin.reboot:
      when: swapsize_check.stdout == "not_found"

    - name: Install OS Deps
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
        - alsa-utils
        - git
        - curl
        - raspberrypi-kernel-headers
        - dkms
        - i2c-tools
        - libasound2-plugins
        - alsa-utils

    - name: Clone Wyoming Satellite
      ansible.builtin.git:
        repo: "{{ wyoming_satellite_repo }}"
        dest: ~/wyoming-satellite
        version: "{{ wyoming_satellite_tag }}"

    - name: Clone OpenWakeWord
      ansible.builtin.git:
        repo: "{{ openwakeword_repo }}"
        dest: ~/wyoming-openwakeword
        version: "{{ openwakeword_tag }}"

    - name: Check if the file exists
      ansible.builtin.stat:
        path: /lib/systemd/system/seeed-voicecard.service
      register: seeed_voicecard_check

    - name: Install Audio Drivers
      become: true
      script: scripts/audio-drivers-WM8960.sh
      when: not seeed_voicecard_check.stat.exists

    - name: Reboot to enable audio drivers
      become: true
      ansible.builtin.reboot:
      when: not seeed_voicecard_check.stat.exists

    - name: Create virtual environment for wyoming satellite
      ansible.builtin.command:
        cmd: python3 -m venv ~/wyoming-satellite/.venv
      args:
        creates: ~/wyoming-satellite/.venv

    - name: Update pip wyoming-satellite
      pip:
        virtualenv: ~/wyoming-satellite/.venv
        extra_args: --upgrade
        virtualenv_python: python3
        name: pip

    - name: Update wheel & setuptools for wyoming satellite
      pip:
        virtualenv: ~/wyoming-satellite/.venv
        extra_args: --upgrade
        virtualenv_python: python3
        name: "{{ item }}"
      loop:
        - wheel
        - setuptools

    - name: Install pip requirements for wyoming satellite
      pip:
        requirements: "{{ item }}"
        virtualenv: ~/wyoming-satellite/.venv
        extra_args: -f 'https://synesthesiam.github.io/prebuilt-apps/'
        virtualenv_python: python3
      loop:
        - ~/wyoming-satellite/requirements.txt
        - ~/wyoming-satellite/requirements_audio_enhancement.txt
        - ~/wyoming-satellite/requirements_vad.txt

    - name: Setup OpenWakeWord
      args:
        chdir: ~/wyoming-openwakeword
        # Janky, there is probably a much better way...
        creates: ~/wyoming-openwakeword/.venv/share/python-wheels/toml-0.10.1-py2.py3-none-any.whl
      ansible.builtin.command:
        cmd: script/setup

    - name: Create OpenWakeWord Service (Base)
      become: true
      template: src=../templates/wyoming-openwakeword.service dest=/etc/systemd/system/wyoming-openwakeword.service

    - name: Assert OpenWakeWord service is active & running
      become: true
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        enabled: true
        masked: no
        name: wyoming-openwakeword.service

    - name: Create Wyoming Satellite service (Base)
      become: true
      template: src=../templates/wyoming-satellite.service dest=/etc/systemd/system/wyoming-satellite.service

    - name: Assert Wyoming Satellite service is active & running
      become: true
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        enabled: true
        masked: no
        name: wyoming-satellite.service